services:
  - type: web
    name: baccarat-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 7815360317:AAGsrFzeUZrHOjujf5aY2UjlBj4GOblHSig
      - key: PORT
        value: 10000
    plan: free
